# Generated by Django 4.0.4 on 2022-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocznik', models.IntegerField(default=None)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=20)),
                ('kolor', models.CharField(max_length=15)),
                ('generacja', models.IntegerField(default=None)),
            ],
        ),
    ]
