# Generated by Django 4.0.4 on 2022-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kierowca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('doswiadczenie', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterModelOptions(
            name='samochod',
            options={'verbose_name': 'Marka'},
        ),
    ]
