# Generated by Django 4.0.4 on 2022-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_kierowca_alter_samochod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubezpieczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubezpieczenie', models.CharField(max_length=20)),
                ('koszt_ubezpieczenia', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'Insurance',
            },
        ),
        migrations.AlterModelOptions(
            name='kierowca',
            options={'verbose_name': 'Name'},
        ),
        migrations.AlterModelOptions(
            name='samochod',
            options={'verbose_name': 'Brand'},
        ),
    ]
